/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: perf.c
  Source: perf.idl
  Cyclone DDS: V0.8.0

*****************************************************************/
#include "perf.h"

static const uint32_t performance_timestamp_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (performance_timestamp, sec),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (performance_timestamp, nsec),
  DDS_OP_RTS
};

const dds_topic_descriptor_t performance_timestamp_desc =
{
  sizeof (performance_timestamp),
  8u,
  DDS_TOPIC_FIXED_SIZE,
  0u,
  "performance::timestamp",
  NULL,
  3,
  performance_timestamp_ops,
  ""
};
static const uint32_t performance_performance_profile_ops [] =
{
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (performance_performance_profile, sample_size),
  DDS_OP_ADR | DDS_OP_TYPE_4BY, offsetof (performance_performance_profile, n_samples),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (performance_performance_profile, t.sec),
  DDS_OP_ADR | DDS_OP_TYPE_8BY | DDS_OP_FLAG_FP, offsetof (performance_performance_profile, t.nsec),
  DDS_OP_ADR | DDS_OP_TYPE_SEQ | DDS_OP_SUBTYPE_1BY, offsetof (performance_performance_profile, buf),
  DDS_OP_RTS
};

const dds_topic_descriptor_t performance_performance_profile_desc =
{
  sizeof (performance_performance_profile),
  8u,
  DDS_TOPIC_NO_OPTIMIZE,
  0u,
  "performance::performance_profile",
  NULL,
  6,
  performance_performance_profile_ops,
  ""
};
